---
czertainly:
  appliance_version: 0.5.0
  branding:
    repo: https://github.com/semik/CZERTAINLY-Appliance-Branding.git
    branch: develop
  host_config:
    repo: https://github.com/semik/CZERTAINLY-Appliance-Host-Config.git
    branch: develop
  rke2:
    repo: https://github.com/semik/CZERTAINLY-Appliance-RKE2.git
    branch: develop
czertainly_netinstall_iso_name: czertainly-appliance-netinstall-{{ czertainly.appliance_version }}.iso
wdir: tmp
netinst_image:
  name:   debian-11.5.0-amd64-netinst.iso
  URL:    https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/
  SHA256: e307d0e583b4a8f7e5b436f8413d4707dd4242b70aea61eb08591dc0378522f3
